plugins {
    id 'com.android.application'
}

android {
    namespace 'com.moneymanagement.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.moneymanagement.app'
        minSdk 24
        targetSdk 35
        versionCode 4
        versionName '1.4.0-loans'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
